### ISSUE TITLE
redscript error on game launch

### ISSUE THREAD

**Issue by TGCAmris** [psiberx/cp2077-rewind#1]
Hey, Pavel! First: that you are scripting this is great! I've been sorely missing this feature in cp2077! 

Now: I've tried to install this for the current game version 2.1 and get a redscript error on launch. The error message says the error is caused by Night City Rewind mod. It says the game would start anyway but redscript would be disabled and the mods not work. I have codeware 1.6.0 and rescript 0.5.16 installed. So my guess is the error is caused by the mod not updated to version 2.1 yet?

Btw_ Your idea of making it possible to rewind the cyberpsychos as well is very cool. I would love that. 

(And if you'd somehow find the time to make any other side missions rewindable I'd totally love that too!)

Thank you so much for your work!

**Comment by psiberx** [comment]
Hi. You have to read redscript log to know the actual error.

**Comment by TGCAmris** [comment]
Ah, thx!  This is interesting. I copied the log file. Maybe it'll help.

[INFO - Thu, 14 Dec 2023 12:00:20 +0100] Using defaults for the script manifest (manifest not present)
[INFO - Thu, 14 Dec 2023 12:00:20 +0100] Bundle path provided: C:\Games\steamapps\common\Cyberpunk 2077\r6\cache\modded\final.redscripts
[INFO - Thu, 14 Dec 2023 12:00:20 +0100] Compiling files in C:\Games\steamapps\common\Cyberpunk 2077\r6\scripts:
ArchiveXL\ArchiveXL.reds
Codeware\Codeware.Global.reds
Codeware\Codeware.Localization.reds
Codeware\Codeware.reds
Codeware\Codeware.UI.reds
Codeware\Codeware.UI.TextInput.reds
NightCityRewind\NightCityRewind.Global.reds
NightCityRewind\NightCityRewind.reds
Tduality\unlock_me_the_mods.reds
TweakXL\TweakXL.reds
UpgradeWeaponsUnlocked\UpgradeWeaponsUnlocked.reds
[ERROR - Thu, 14 Dec 2023 12:00:20 +0100] [UNRESOLVED_MEMBER] At C:\Games\steamapps\common\Cyberpunk 2077\r6\scripts\NightCityRewind\NightCityRewind.reds:29:18:
            case OpenWorldActivityResult.NotFinished:
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
member NotFinished not found on OpenWorldActivityResult

[ERROR - Thu, 14 Dec 2023 12:00:20 +0100] [NO_MATCHING_OVERLOAD] At C:\Games\steamapps\common\Cyberpunk 2077\r6\scripts\NightCityRewind\NightCityRewind.reds:40:13:
            new OpenWorldActivityRequest(
            ^^^
expected 4 arguments for OpenWorldActivityRequest

**Comment by psiberx** [comment]
I uploaded the latest version that works on current patch.
